// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/garcialuis/Gossip/client/models"
)

// CreatePostReader is a Reader for the CreatePost structure.
type CreatePostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreatePostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreatePostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreatePostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreatePostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreatePostCreated creates a CreatePostCreated with default headers values
func NewCreatePostCreated() *CreatePostCreated {
	return &CreatePostCreated{}
}

/*CreatePostCreated handles this case with default header values.

Post model
*/
type CreatePostCreated struct {
	Payload *models.Post
}

func (o *CreatePostCreated) Error() string {
	return fmt.Sprintf("[POST /posts][%d] createPostCreated  %+v", 201, o.Payload)
}

func (o *CreatePostCreated) GetPayload() *models.Post {
	return o.Payload
}

func (o *CreatePostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Post)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePostUnauthorized creates a CreatePostUnauthorized with default headers values
func NewCreatePostUnauthorized() *CreatePostUnauthorized {
	return &CreatePostUnauthorized{}
}

/*CreatePostUnauthorized handles this case with default header values.

Unauthorized
*/
type CreatePostUnauthorized struct {
}

func (o *CreatePostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /posts][%d] createPostUnauthorized ", 401)
}

func (o *CreatePostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePostUnprocessableEntity creates a CreatePostUnprocessableEntity with default headers values
func NewCreatePostUnprocessableEntity() *CreatePostUnprocessableEntity {
	return &CreatePostUnprocessableEntity{}
}

/*CreatePostUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type CreatePostUnprocessableEntity struct {
}

func (o *CreatePostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /posts][%d] createPostUnprocessableEntity ", 422)
}

func (o *CreatePostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePostInternalServerError creates a CreatePostInternalServerError with default headers values
func NewCreatePostInternalServerError() *CreatePostInternalServerError {
	return &CreatePostInternalServerError{}
}

/*CreatePostInternalServerError handles this case with default header values.

Internal Server Error
*/
type CreatePostInternalServerError struct {
}

func (o *CreatePostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /posts][%d] createPostInternalServerError ", 500)
}

func (o *CreatePostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
