// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreatePostParams creates a new CreatePostParams object
// with the default values initialized.
func NewCreatePostParams() *CreatePostParams {

	return &CreatePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePostParamsWithTimeout creates a new CreatePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreatePostParamsWithTimeout(timeout time.Duration) *CreatePostParams {

	return &CreatePostParams{

		timeout: timeout,
	}
}

// NewCreatePostParamsWithContext creates a new CreatePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreatePostParamsWithContext(ctx context.Context) *CreatePostParams {

	return &CreatePostParams{

		Context: ctx,
	}
}

// NewCreatePostParamsWithHTTPClient creates a new CreatePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreatePostParamsWithHTTPClient(client *http.Client) *CreatePostParams {

	return &CreatePostParams{
		HTTPClient: client,
	}
}

/*CreatePostParams contains all the parameters to send to the API endpoint
for the create post operation typically these are written to a http.Request
*/
type CreatePostParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create post params
func (o *CreatePostParams) WithTimeout(timeout time.Duration) *CreatePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create post params
func (o *CreatePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create post params
func (o *CreatePostParams) WithContext(ctx context.Context) *CreatePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create post params
func (o *CreatePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create post params
func (o *CreatePostParams) WithHTTPClient(client *http.Client) *CreatePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create post params
func (o *CreatePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
