// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeletePostParams creates a new DeletePostParams object
// with the default values initialized.
func NewDeletePostParams() *DeletePostParams {
	var ()
	return &DeletePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePostParamsWithTimeout creates a new DeletePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePostParamsWithTimeout(timeout time.Duration) *DeletePostParams {
	var ()
	return &DeletePostParams{

		timeout: timeout,
	}
}

// NewDeletePostParamsWithContext creates a new DeletePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePostParamsWithContext(ctx context.Context) *DeletePostParams {
	var ()
	return &DeletePostParams{

		Context: ctx,
	}
}

// NewDeletePostParamsWithHTTPClient creates a new DeletePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePostParamsWithHTTPClient(client *http.Client) *DeletePostParams {
	var ()
	return &DeletePostParams{
		HTTPClient: client,
	}
}

/*DeletePostParams contains all the parameters to send to the API endpoint
for the delete post operation typically these are written to a http.Request
*/
type DeletePostParams struct {

	/*ID
	  The identification key

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete post params
func (o *DeletePostParams) WithTimeout(timeout time.Duration) *DeletePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete post params
func (o *DeletePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete post params
func (o *DeletePostParams) WithContext(ctx context.Context) *DeletePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete post params
func (o *DeletePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete post params
func (o *DeletePostParams) WithHTTPClient(client *http.Client) *DeletePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete post params
func (o *DeletePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete post params
func (o *DeletePostParams) WithID(id int64) *DeletePostParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete post params
func (o *DeletePostParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
