// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/garcialuis/Gossip/client/models"
)

// GetPostsReader is a Reader for the GetPosts structure.
type GetPostsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPostsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPostsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetPostsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPostsOK creates a GetPostsOK with default headers values
func NewGetPostsOK() *GetPostsOK {
	return &GetPostsOK{}
}

/*GetPostsOK handles this case with default header values.

List of Posts
*/
type GetPostsOK struct {
	Payload []*models.Post
}

func (o *GetPostsOK) Error() string {
	return fmt.Sprintf("[GET /posts][%d] getPostsOK  %+v", 200, o.Payload)
}

func (o *GetPostsOK) GetPayload() []*models.Post {
	return o.Payload
}

func (o *GetPostsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPostsInternalServerError creates a GetPostsInternalServerError with default headers values
func NewGetPostsInternalServerError() *GetPostsInternalServerError {
	return &GetPostsInternalServerError{}
}

/*GetPostsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetPostsInternalServerError struct {
}

func (o *GetPostsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /posts][%d] getPostsInternalServerError ", 500)
}

func (o *GetPostsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
