// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/garcialuis/Gossip/client/models"
)

// GetPostReader is a Reader for the GetPost structure.
type GetPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPostOK creates a GetPostOK with default headers values
func NewGetPostOK() *GetPostOK {
	return &GetPostOK{}
}

/*GetPostOK handles this case with default header values.

Post model
*/
type GetPostOK struct {
	Payload *models.Post
}

func (o *GetPostOK) Error() string {
	return fmt.Sprintf("[GET /post/{id}][%d] getPostOK  %+v", 200, o.Payload)
}

func (o *GetPostOK) GetPayload() *models.Post {
	return o.Payload
}

func (o *GetPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Post)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPostBadRequest creates a GetPostBadRequest with default headers values
func NewGetPostBadRequest() *GetPostBadRequest {
	return &GetPostBadRequest{}
}

/*GetPostBadRequest handles this case with default header values.

Bad Request
*/
type GetPostBadRequest struct {
}

func (o *GetPostBadRequest) Error() string {
	return fmt.Sprintf("[GET /post/{id}][%d] getPostBadRequest ", 400)
}

func (o *GetPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPostInternalServerError creates a GetPostInternalServerError with default headers values
func NewGetPostInternalServerError() *GetPostInternalServerError {
	return &GetPostInternalServerError{}
}

/*GetPostInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetPostInternalServerError struct {
}

func (o *GetPostInternalServerError) Error() string {
	return fmt.Sprintf("[GET /post/{id}][%d] getPostInternalServerError ", 500)
}

func (o *GetPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
