// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUpdatePostParams creates a new UpdatePostParams object
// with the default values initialized.
func NewUpdatePostParams() *UpdatePostParams {
	var ()
	return &UpdatePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePostParamsWithTimeout creates a new UpdatePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePostParamsWithTimeout(timeout time.Duration) *UpdatePostParams {
	var ()
	return &UpdatePostParams{

		timeout: timeout,
	}
}

// NewUpdatePostParamsWithContext creates a new UpdatePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdatePostParamsWithContext(ctx context.Context) *UpdatePostParams {
	var ()
	return &UpdatePostParams{

		Context: ctx,
	}
}

// NewUpdatePostParamsWithHTTPClient creates a new UpdatePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdatePostParamsWithHTTPClient(client *http.Client) *UpdatePostParams {
	var ()
	return &UpdatePostParams{
		HTTPClient: client,
	}
}

/*UpdatePostParams contains all the parameters to send to the API endpoint
for the update post operation typically these are written to a http.Request
*/
type UpdatePostParams struct {

	/*ID
	  The identification key

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update post params
func (o *UpdatePostParams) WithTimeout(timeout time.Duration) *UpdatePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update post params
func (o *UpdatePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update post params
func (o *UpdatePostParams) WithContext(ctx context.Context) *UpdatePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update post params
func (o *UpdatePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update post params
func (o *UpdatePostParams) WithHTTPClient(client *http.Client) *UpdatePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update post params
func (o *UpdatePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update post params
func (o *UpdatePostParams) WithID(id int64) *UpdatePostParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update post params
func (o *UpdatePostParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
