// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/garcialuis/Gossip/client/models"
)

// UpdatePostReader is a Reader for the UpdatePost structure.
type UpdatePostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdatePostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdatePostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdatePostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdatePostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdatePostNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdatePostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdatePostOK creates a UpdatePostOK with default headers values
func NewUpdatePostOK() *UpdatePostOK {
	return &UpdatePostOK{}
}

/*UpdatePostOK handles this case with default header values.

Post model
*/
type UpdatePostOK struct {
	Payload *models.Post
}

func (o *UpdatePostOK) Error() string {
	return fmt.Sprintf("[PUT /post/{id}][%d] updatePostOK  %+v", 200, o.Payload)
}

func (o *UpdatePostOK) GetPayload() *models.Post {
	return o.Payload
}

func (o *UpdatePostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Post)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdatePostBadRequest creates a UpdatePostBadRequest with default headers values
func NewUpdatePostBadRequest() *UpdatePostBadRequest {
	return &UpdatePostBadRequest{}
}

/*UpdatePostBadRequest handles this case with default header values.

Bad Request
*/
type UpdatePostBadRequest struct {
}

func (o *UpdatePostBadRequest) Error() string {
	return fmt.Sprintf("[PUT /post/{id}][%d] updatePostBadRequest ", 400)
}

func (o *UpdatePostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdatePostUnauthorized creates a UpdatePostUnauthorized with default headers values
func NewUpdatePostUnauthorized() *UpdatePostUnauthorized {
	return &UpdatePostUnauthorized{}
}

/*UpdatePostUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdatePostUnauthorized struct {
}

func (o *UpdatePostUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /post/{id}][%d] updatePostUnauthorized ", 401)
}

func (o *UpdatePostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdatePostNotFound creates a UpdatePostNotFound with default headers values
func NewUpdatePostNotFound() *UpdatePostNotFound {
	return &UpdatePostNotFound{}
}

/*UpdatePostNotFound handles this case with default header values.

Post Not Found
*/
type UpdatePostNotFound struct {
}

func (o *UpdatePostNotFound) Error() string {
	return fmt.Sprintf("[PUT /post/{id}][%d] updatePostNotFound ", 404)
}

func (o *UpdatePostNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdatePostUnprocessableEntity creates a UpdatePostUnprocessableEntity with default headers values
func NewUpdatePostUnprocessableEntity() *UpdatePostUnprocessableEntity {
	return &UpdatePostUnprocessableEntity{}
}

/*UpdatePostUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type UpdatePostUnprocessableEntity struct {
}

func (o *UpdatePostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /post/{id}][%d] updatePostUnprocessableEntity ", 422)
}

func (o *UpdatePostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
