apiVersion: v1
kind: Service
metadata:
  name: gossip
  labels:
    app: gossip
    tier: service
spec:
  # use NodePort here to be able to access a port on each node
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31710
  selector:
    app: gossip