apiVersion: v1
kind: Pod
metadata:
  name: gossip
  labels:
    language: go
    env: test
spec:
  containers:
  - name: gossip
    image: gossip:0.0.5
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: DB_POSTGRES_DRIVER
      value: "postgres"
    - name: DB_USER
      value: ""
    - name: DB_PASSWORD
      value: ""
    - name: DB_HOST
      value: ""
    - name: DB_NAME
      value: ""
    - name: DB_PORT
      value: ""